keys:
  - &admin_gotlou age10u2sm27epp9d5ksg4egxraskh5fwgqrqng8fwcmgetcuzff4vczs5ul2tn 
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
    
      age:
      - *admin_gotlou