{
  lib,
  stdenv,
  fetchFromGitHub,
  python3,
  litert-lm-api,
  makeWrapper,
}:

let
  python = python3;
  version = "0.11.0-unstable-2026-05-05";

  src = fetchFromGitHub {
    owner = "google-ai-edge";
    repo = "litert-lm";
    rev = "4541df063d3f981037b8375bcfe8656dd3ad99c0";
    hash = "sha256-3Sb/2oA0SKvmpMyJWVO3QVh8iangd6WFwK2lfMqNbzE=";
  };

  # Create a Python environment with all needed packages
  pythonEnv = python.withPackages (
    ps: with ps; [
      click
      huggingface-hub
      prompt-toolkit
    ]
  );

in
stdenv.mkDerivation {
  pname = "litert-lm";
  inherit version src;

  nativeBuildInputs = [
    makeWrapper
  ];

  dontBuild = true;

  installPhase = ''
        # Create lib directory for Python packages
        mkdir -p $out/lib/python3/site-packages/litert_lm_cli
        mkdir -p $out/bin

        # Copy the CLI Python package (only .py files, skip tests)
        for f in $src/python/litert_lm_cli/*.py; do
          base=$(basename "$f")
          case "$base" in
            *_test.py) continue ;;
            *) cp "$f" $out/lib/python3/site-packages/litert_lm_cli/ ;;
          esac
        done

        # Create version.py (generated by Bazel during normal build)
        cat > $out/lib/python3/site-packages/litert_lm_cli/version.py << 'EOF'
    VERSION = "${version}"
    EOF

        # Create a simple __init__.py
        touch $out/lib/python3/site-packages/litert_lm_cli/__init__.py

        # Create the wrapper script using the proper Python environment
        makeWrapper ${pythonEnv.interpreter} $out/bin/litert-lm \
          --prefix PYTHONPATH : "$out/lib/python3/site-packages" \
          --prefix PYTHONPATH : "${litert-lm-api}/lib/python3/site-packages" \
          --add-flags "-m litert_lm_cli.main"
  '';

  meta = with lib; {
    description = "CLI tool for LiteRT-LM, Google's high-performance on-device LLM inference framework";
    homepage = "https://github.com/google-ai-edge/litert-lm";
    license = licenses.asl20;
    mainProgram = "litert-lm";
    platforms = litert-lm-api.meta.platforms;
    maintainers = [ ];
  };
}
