{
  imports = [
    ./bluetooth.nix
    ./colord.nix
    ./sudo-rs.nix
    ./nix.nix
    ./zram.nix
    ./standard-services.nix
    ./syncthing.nix
    ./openssh.nix
    ./opensnitch.nix
    ./keyd.nix
    ./time.nix
    ./warp.nix
    ./virt.nix
    ./dns-resolver.nix
    ./oom.nix
    ./networking.nix
  ];
}
